### ISSUE TITLE
Embed Video Instructions

### ISSUE THREAD

**Issue by pmack1** [pmack1/CensusMap#9]

**Comment by nsmader** [comment]
Tasks include:

* Creating a YouTube account for the cnat@chapinhall.org e-mail
* Posting current video
* Updating new one when ready

**Comment by nsmader** [comment]
YouTube account has been created, and mock-up video is up at [this link](https://youtu.be/iVGEerpIVeQ).

**Comment by pmack1** [comment]
Embedded draft video into Directions section. Feed back on location and size of the video iframe are welcome.
